List<String> isiPengertian = [
  "Arti Qadha\n\n\nMenurut bahasa Qadha adalah kehendak atau ketetapan hukum\nMenurut istilah Qadha adalah kehendak atau ketetapan hukum Allah subhanahu wata\’ala terhadap makhluknya atas segala sesuatu yang akan terjadi didunia dan akhirat",
  "Arti Qadar\n\n\nMenurut bahasa Qadar adalah ukuran atau ketentuan\nMenurut istilah Qadar adalah segala ukuran atau ketentuan Allah subhanahu wata\’ala terhadap makhluknya atas segala sesuatu yang telah terjadi",
  "Qadha dan Qodar dapat digabung menjadi satu istilah yang disebut takdir. Sehingga, takdir dapat diartikan segala ketentuan atau ketetapan Allah terhadap makhluknya atas segala sesuatu yang akan terjadi maupun telah terjadi di dunia dan akhirat",
  "Perbedaan Qhada dan Qadar\n\n\nKelahiran, kematian, warna kulit, dan bentuk wajah adalah ketentuan Allah yang tidak bisa ditawar. Kita tidak dapat menentukan kelahirankita sendiri, seperti warna kulit, bentuk wajah, dan lain sebagainya. Ketentuan Allah yang telah ditentukan oleh-Nya pada zaman azali disebut Qadha.\n\nAdapun ketentuan Allah yang ditetapkan-Nya atas manusia setelah berusaha dan berdo’a itu disebut Qadar. Allah telah menetukan umur, rezeki, dan kemantian manusia. Tetapi manusia diberi hak untuk menentukn pilihan hidupnya masing-masing. Jika ingin pandai maka ia harus belajar. Jika ingin bisa maka ia harus mencoba. Jika ingin sukses maka ia harus bersungguh-sungguh."
];

List<String> isiHubungan = [
  "Iman kepada qadha dan qadar adalah percaya dan yakin sepenuhnya bahwa Allah telah menentukan tentang segala sesuatu bagi makhluk-Nya. Walaupun manusia telah ditetapkan nasibnya, tidak berarti manusia hanya tinggal diam menunggu nasib tanpa ikhtiar. Takdir bukanlah alasan untuk malas berusaha dan berbuat.",
  "Mengenai hubungan antara qadha dan qadar dengan ikhtiar, para ulama berpendapat bahwa takdir itu ada dua macam.\n\n1. Mu’alaq : Takdir yang erat kaitannya dengan ikhtiar manusi.\nContoh : kesembuhan penyakit, keberhasilan siswa dalam belajar, kaya atau miskin, dan lain sebgainya.\n\n2. Mubram : Takdir yang terjadi pada diri manusia dan tidak dapat diushakan atau diubah.\nContoh : matinya makkhluk Allah, terjadinya hari kiamat, turunnya hujan, tanah longsor, robohnya pohon, jatuuhnya daun, jenis kelamin, dann lain-lain.",
  "Orang yang mengimani qadha dan qadar Allah tidak akan putus asa Ketika tertipa suatu bencana dan tidak sombong Ketika sukses. Manusia juga tidak boleh menyerah pada takdir. Bansa terbelakang harus lebih berusaha dengan keras untuk dapat maju dan mengubah sifat malas, tidak disiplin, dan sembrono menjadi sifat yang bersemamgat, disiplin, dan teliti. Dengan demikian, bangsa itu menjadi maju dan berkemban. Allah subhanhu wata’ala berfirman :\n\n" +
      "إِنَّ اللَّهَ لاَ يُغَيِّرُ مَا بِقَوْمٍ حَتَّى يُغَيِّرُ مَا بِأَنْفُسِهم" +
      "\n\nArtinya :sesungguhnya Allah tidak akan mengubah keadaan suatu kaum sebelum mereka mengubah keaddaan diri mereka sedendiri ( Q.S. Ar-Ra’d : 11 )  ",
  "Manusia yang beriman kepada qadha dan qadar Allah subhanuahu wata’ala tidak akan putus asa Ketika tertimpa suatu banana dan tidak sombong Ketika sukses.\nTakdir adalah rahasia Allah subhanahu wata’ala tidak ada seorangpun yang dapat mengetahuinya.\nMisalnya : Ia melakukan upaya makan untuk menghindari bahaya sakit atau ia bekerja supaya mendapatkan rezeki untuk menghidupi keluarganya. Dengan demikian, seorang muslim harus bergembira dan selalu optimmis menatap masa depannya. Sebab, Allah telah memberikan takdir yang baik kepada para hamba-Nya yang berprasangka baik kepada-Nya dengan bersungguh-sungguh dan ikhtiar."
];

List<String> isiKetentuan = [
  "Warna kulitmu, kebangsaanmu, dan tempat kelahiranmu adalah takdir Allah yang sudah tidak dapat ditawar dan dihindari lagi. Inilah takdir yang tetap dan sudah kita ketahui bersama.",
  "Sekarang bagaimana dengan orang yang berbuat baik dan jahat? Apakah perbuatan mereka juga termasuk takdir Allah? Apakah Allah yang menciptakan perbuatan atas manusia? Jika begitu layakkah orang yang berdosa karena takdir Allah mendapat siksa neraka?\n\nBetul, ini takdir Allah subhanahu wata’ala juga. Tetapi hal ini berbeda dengan takdir yang sudah tetap dan kita ketahui Bersama. Takdir yang satu ini belum kita ketahui dan belum kita lakukan.",
  "Bukankah kita tidak tau apa yang akan kita kerjakan esok? Jika kita tahu apa yang akan kita kerjakan esok, lalu mengapa kita mesti merencanakan untuk berbuat jahat? Bukankah manusia diberi otak oleh Allah untuk berfikir?\n\nDengan otak, manusia dapat memilih untuk mengerjakan perbuatan yang baik dan menghindari yang jahat. Jika ternyata manusia itu memiliih untuk berbuat jahat, bukankah itu daldam Tindakan lari dari takdir yang baik?\n\nTidak bisa dikatakan bahwa orang yang berbuat jahat itu karena memang ditakdirkan Allah untuk berbuat jahat. Dan orang  yang berbuat  baik itu karena memang ditakdirkan bberbuat baik. Jadi manusia itu diberi kebebasan untuk memilih jalan takwa atau jalan dosa.\n\nSedangkan Allah yang mentakdirkan manusia untuk dapat melakukan suatu perbuatan. Adapun dalam kehidupan sehari-hari, kita harus menerima kenyataan. Bahwa, Allah menciptakan nasib manusia berbeda-beda. Tidak mungkin manusia ditakdirkan semuanya mempunyai nasib yang sama. Kita harus berusaha dan berdo’a sedangkn hasilnya kita serahkan kepada Allah.",
  "Pengaruh beriman kepada qadha dan qadar\n\n1. Keberanian, pantang mundur, dan tidak tunduk kepada kekuatan siapapun di dunia ini\n2. Terbebas dari penyakit tinggi hati, sebab ia Cuma mampu berusaha, yang memberi keberhasilan adalah Allah\n3. Sabar dan tidak putus asa. Semangat dalam beramal, bekerja dan bertawakkal kepada Allah\n4. Tenang dalam mengarungi kehidupan, sebab segala sesuatu berjalan sesuai dengan takdir Allah. Dia Maha Mengetahui, sementara manusia tidak."
];

List<String> isiDalil = [
  "Allah subhanahu wata’ala menciptakan segala sesuatu menurut ukuran atau ketentuan teertentu. Hal tersebut sebagaimana dalam firman-Nya\n\nQ.S. At-Talaq : 3\n" +
      "إِنَّ اللّهَ بَالِغُ أَمْرِهِ قَدْ جَعَلَ اللّهُ لِكُلِّ شَيءٍ قَدْرًا" +
      "\n\nArtinya : sesungguhnya Allah melaksanakan urusan (yang dikehendaki-Nya). Sungguh Allah telah mengadakan ketentuan bagi tiap sesuatu",
  "Allah Maha mengetahui segala sesuatu yang akan, sedang, dan telah terjadi. Hanya Dialah yang dapat menentukan segala sesuatu. Sebagaimana Allah berfirman :\n\nQ.S. Al-An’am : 59\n" +
      "وَعِندَهُ مَفَاتِحُ الغَيْبِ لاَ يَعْلَمُهَا إِلاَّ هُوَ وَيَعْلَمُ مَا فِي الْبَرِّ وَالْبَحْرِ وَمَا تَسْقُطُ مِنْ وَرَقَةِ إِلاَّ يَعْلَمُهَا وَلاَ حَبَّةٍ فِي ظُلُمَاتِ الأَرْضِ وَلاَ رَطْبٍ وَلاَ يَابِسٍ إِلاَّ فِي كِتَابٍ مُبِينٍ" +
      "\n\nArtinya : Dan pada sisi Allah-lah kunci-kunci semua yang ghaib, tidak ada yang mengetahuinya kecuali Dia sendiri, dan Dia mengetahui apa yang ada di daratan dan lautan, dan tiada sehelai daunpun yang gugur melainkan Dia mengetahuinya (pula), dan tidak jatuh sebutir bijipun dalam kegelapan bumi dan tidak sesuatu yang basah atau yang kering, melainkan tertulis dalam kitab yang nyata (lauhul mahfudz)",
];

List kumpulanData = [isiPengertian, isiHubungan, isiKetentuan, isiDalil];
